name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg USUARIO_VOLUME_NAME=$(whoami) --build-arg USUARIO_VOLUME_UID=$(id -u) --build-arg USUARIO_VOLUME_GID=$(id -g) --tag php83-phalcon:$(date +%s)
